-- 0017_requisition_consecutive.sql
-- Adds a sequential consecutive number to requisitions

-- 1. Add the column
ALTER TABLE public.requisitions 
ADD COLUMN IF NOT EXISTS consecutive INT8 GENERATED BY DEFAULT AS IDENTITY;

-- 2. (Optional) If you want to start from a specific number, e.g., 100
-- ALTER TABLE public.requisitions ALTER COLUMN consecutive RESTART WITH 100;

-- 3. Comment for clarity
COMMENT ON COLUMN public.requisitions.consecutive IS 'Secuencial para formato visual REQ-000000';
